remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Predicting Unemployment During Economic Downturns
description: This project explores whether we can use past data on industry trends and leading indicators to predict future employment and economic trends
